version: '3'

services:
  web:
    image: web
    build:
      context: ./Web
      dockerfile: Dockerfile
    links:
      - apix

  apix:
    image: apix
    build:
      context: ./ApiX
      dockerfile: Dockerfile
