apiVersion: v1
kind: Service
metadata:
  name: demo-web
  labels:
    name: demo-web
spec:
  selector:
    service: demo-web
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP